# Site Settings
title: Matias Tassano
email: tasso.matias@gmail.com
description: >
  Homepage of Matias Tassano.
baseurl: ""
url: "https://m-tassano.github.io"
linkedin_username: matias-tassano
github_username: m-tassano
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
