markdown: kramdown
kramdown:
  input: GFM
# Site settings
title: Matias Tassano
description: Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m-tassano.github.io"

# User settings
username: Matias Tassano
user_description: I am Research Engineer at Facebook Reality Labs based in Zurich. Previously, I was as a Senior Engineer at GoPro Paris, where I worked for over 5 years. My research interests include neural networks for image and video restoration, computer vision, image processing, and embedded systems. I've also worked on control theory. I obtained a PhD in Applied Mathematics from <a href="https://www.univ-paris5.fr/">Paris Descartes University</a>, a master's degree in Applied Mathematics from <a href="https://ens-paris-saclay.fr/">ENS Cachan</a>, and a master's degree in Electrical Engineering from <a href="https://www.fing.edu.uy/">Universidad de la República</a>.
user_title: Research Engineer @ Facebook Reality Labs
email: tasso.matias@gmail.com
github_username:  m-tassano
linkedin_username: matias-tassano

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# Build Settings
#sass:
#  sass_dir: _sass
# include: ['_pages']

