# Site Settings
title: Matias Tassano
email: tasso.matias@gmail.com
description: >
  Senior Engineer at GoPro Paris. PhD from Paris Descartes University.
baseurl: ""
url: "http://0.0.0.0:4000"
linkedin_username: matias-tassano
github_username: m-tassano
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
